# Generated by Django 2.1.15 on 2021-08-28 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('likes', models.TextField(default='', help_text='A few things the dog likes', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('u', 'Unavailable'), ('r', 'Reserved'), ('s', 'Sold')], default='a', help_text='status of the dog', max_length=1)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Breed')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('d', 'Dogs'), ('c', 'Cats'), ('b', 'Birds')], default='d', help_text='type of the pet', max_length=1)),
                ('pet_feature', models.CharField(choices=[('f', 'Fly'), ('s', 'Swim'), ('r', 'Run')], help_text='What pet can do.', max_length=1)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Pet'),
        ),
    ]
